"""
Weather tool for the SynthLang Proxy.

This module provides a tool for getting weather information.
"""
import logging
import random
import sys
import os
import traceback
from typing import Dict, Any, Optional

# Add the project root to the Python path
project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
if project_root not in sys.path:
    sys.path.insert(0, project_root)
    print(f"Added {project_root} to Python path in weather.py")

# Print current Python path for debugging
print(f"Python path in weather.py: {sys.path}")

# Try to import from src.app first
try:
    print("Attempting to import registry from src.app.agents.registry")
    from src.app.agents.registry import register_tool
    print("Successfully imported registry from src.app.agents.registry")
except ImportError as e:
    print(f"Error importing from src.app.agents.registry: {e}")
    print(f"Traceback: {traceback.format_exc()}")
    # Try to import from app
    try:
        print("Attempting to import registry from app.agents.registry")
        from app.agents.registry import register_tool
        print("Successfully imported registry from app.agents.registry")
    except ImportError as e2:
        print(f"Error importing from app.agents.registry: {e2}")
        print(f"Traceback: {traceback.format_exc()}")
        # Define a dummy register_tool function to avoid errors
        def register_tool(name, func):
            print(f"Dummy register_tool called for {name}")
        print("Using dummy register_tool function")

# Logger for this module
logger = logging.getLogger(__name__)

async def get_weather(location: str, user_message: Optional[str] = None, user_id: Optional[str] = None) -> Dict[str, Any]:
    """
    Get weather information for a location.
    
    Args:
        location: The location to get weather for
        user_message: The original user message (optional)
        user_id: The ID of the user making the request (optional)
        
    Returns:
        A dictionary containing the weather information
    """
    logger.info(f"Getting weather for location: {location}")
    print(f"Getting weather for location: {location}")
    
    try:
        # In a real implementation, we would call a weather API here
        # For now, we'll just return some mock data
        
        # Generate random weather data
        temperature = random.randint(0, 35)
        conditions = random.choice(["Sunny", "Cloudy", "Rainy", "Snowy", "Partly Cloudy"])
        humidity = random.randint(30, 90)
        wind_speed = random.randint(0, 30)
        
        # Create the response
        response = f"""Weather for {location}:

Temperature: {temperature}°C
Conditions: {conditions}
Humidity: {humidity}%
Wind Speed: {wind_speed} km/h

This weather information was generated by the weather tool. In a production environment, this would be real data from a weather API."""
        
        return {
            "content": response,
            "tool": "weather",
            "location": location,
            "temperature": temperature,
            "conditions": conditions,
            "humidity": humidity,
            "wind_speed": wind_speed
        }
    
    except Exception as e:
        error_message = f"""I couldn't get the weather for "{location}".

Error: {str(e)}

Please try again with a different location or check your spelling."""
        
        logger.error(f"Weather error: {str(e)}")
        print(f"Weather error: {str(e)}")
        print(f"Traceback: {traceback.format_exc()}")
        
        return {
            "content": error_message,
            "tool": "weather",
            "location": location,
            "error": str(e)
        }

# Register the tool
try:
    print("Registering weather tool")
    register_tool("weather", get_weather)
    print("Weather tool registered successfully")
except Exception as e:
    print(f"Error registering weather tool: {e}")
    print(f"Traceback: {traceback.format_exc()}")